services:

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data
